<a href="https://colab.research.google.com/github/ishneha1/AI_foundation/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random

#set random seed for reproductibility
np.random.seed(42)

#generate data
num_rows=100
data={
    'User ID' : range(1,num_rows+1),
    'Gender':[random.choice(['Male','Female'])for _ in range(num_rows)],
    'Age':[random.randint(18,65)for _ in range(num_rows)],
    'Estimated Salary':np.random.randint(20000,200000, num_rows),
    'Purchased':np.random.randint(0,2,num_rows)
}
#create dataframe
df=pd.DataFrame(data)
display(df)

User ID  Gender  Age  Estimated Salary  Purchased
0         1  Female   48            141958          0
1         2    Male   23            166867          0
2         3  Female   37            151932          1
3         4    Male   61            123694          0
4         5  Female   24            139879          1
..      ...     ...  ...               ...        ...
95       96    Male   27             59504          0
96       97    Male   50            184231          0
97       98  Female   28             33986          1
98       99  Female   60             81858          0
99      100    Male   59            149312          1

[100 rows x 5 columns]

In [ ]:
df.to_csv('dataset.cv',index=False)

In [ ]:
# import the dataset
df = pd.read_csv('/content/dataset.cv')
df.head(5)

User ID  Gender  Age  Estimated Salary  Purchased
0        1  Female   48            141958          0
1        2    Male   23            166867          0
2        3  Female   37            151932          1
3        4    Male   61            123694          0
4        5  Female   24            139879          1

### Steps :
- Data Preprocessing
- Fitting KNN to the training set
- Prediciting the result
- Test accuracy of the result
- Visualise the result



In [ ]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset=pd.read_csv('/content/dataset.cv')
dataset

User ID  Gender  Age  Estimated Salary  Purchased
0         1  Female   48            141958          0
1         2    Male   23            166867          0
2         3  Female   37            151932          1
3         4    Male   61            123694          0
4         5  Female   24            139879          1
..      ...     ...  ...               ...        ...
95       96    Male   27             59504          0
96       97    Male   50            184231          0
97       98  Female   28             33986          1
98       99  Female   60             81858          0
99      100    Male   59            149312          1

[100 rows x 5 columns]

In [ ]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
display(X)

array([[    48, 141958],
       [    23, 166867],
       [    37, 151932],
       [    61, 123694],
       [    24, 139879],
       [    58, 130268],
       [    37,  74886],
       [    57, 157337],
       [    24, 188266],
       [    39, 107498],
       [    40, 132727],
       [    63, 146324],
       [    49, 195203],
       [    38,  36023],
       [    22,  61090],
       [    60,  87221],
       [    27,  84820],
       [    55,  20769],
       [    20,  79735],
       [    56,  84925],
       [    41,  25311],
       [    39, 123355],
       [    50, 105305],
       [    61, 179765],
       [    41, 150608],
       [    23, 176730],
       [    21, 104478],
       [    51, 142537],
       [    61, 169503],
       [    57, 150523],
       [    38,  22747],
       [    23, 143855],
       [    60,  85725],
       [    27, 149981],
       [    20, 104654],
       [    37, 186845],
       [    65, 139346],
       [    25,  87435],
       [    62,  76886],
       [    31,  86803],


In [ ]:
x=df["Age"].mode()
x

0    39
1    50
Name: Age, dtype: int64

In [ ]:
y=df["Estimated Salary"].median()
y

106056.0

In [ ]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test,= train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
X_train=st_x.fit_transform(X_train)
X_test=st_x.transform(X_test)
X_test

array([[-1.58832369,  0.01977194],
       [ 0.41046567,  0.58579442],
       [-0.44615834,  0.90700293],
       [-1.51693836,  0.76539448],
       [-1.65970903, -0.52031828],
       [-1.01724102,  1.79191553],
       [-1.16001169, -0.34776687],
       [ 0.12492434,  0.14894712],
       [-0.37477301,  1.32997731],
       [-1.16001169, -0.82109134],
       [ 1.19570435,  0.68716768],
       [-1.01724102,  0.76571232],
       [ 1.05293368, -0.01163843],
       [-0.37477301, -1.26010745],
       [ 0.98154835,  1.00805834],
       [-0.37477301, -1.50832422],
       [ 0.48185101,  0.03523408],
       [-0.160617  ,  0.88224856],
       [-1.16001169,  0.87052576],
       [-1.37416769,  1.58632713]])

Fitting K-NN classifier to the Training data : Now we will fit the K-NN classifier to thge training data. To do this we will import the KNeighboursClassifier class of Sklearn Neighbors library. After importing the class, we will create the Classifier object of the class. The Parameter of this class will be

    n_neighbors : To define the required neighbors of the algorithm. Usually, it takes 5.
    metric = 'minkwski' : This is the default parameter and it decides the distance between the points.
    p = 2 : It is equivalent to the standard Euclidean metric.

In [ ]:
# Fitting KNN classifier to the training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

Predicting the Test Result : To predict the test set result, we will create a y_pred vector as we did in Logistic Regression. Below is the code for it :

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])