<a href="https://colab.research.google.com/github/ishneha1/AI_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a[2]=10
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Multidimensional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.zeros((6,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0,1]=20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
n[2]=[1,1,1] #entire row change
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [21]:
n[:,2]=[0,1,2] #rows naherne, column 2 ko replace gara
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [23]:

np.random.rand(3)

array([0.05192633, 0.17596256, 0.33021092])

In [29]:
np.random.seed(23) #seed: same result replicate hunu parcha
np.random.rand(5,2)


array([[0.51729788, 0.9469626 ],
       [0.76545976, 0.28239584],
       [0.22104536, 0.68622209],
       [0.1671392 , 0.39244247],
       [0.61805235, 0.41193009]])

Element-wise operation

In [31]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

Comparison operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a>=2

array([False, False,  True,  True,  True])

In [36]:
b

array([10, 12, 14, 16, 18])

In [37]:
a>b

array([False, False, False, False, False])

Summarizing

In [38]:
a

array([0, 1, 2, 3, 4])

In [39]:
a.std() #standard deviation

1.4142135623730951

In [40]:
a.min()

0

In [41]:
a.max()

4

In [42]:
a.sum()

10